name: CI/CD for Chat App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  black-check:
    runs-on: ubuntu-latest
    name: Black Formatter Check

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 

    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Run Black formatter check
      run: black --check --diff .

  linter-check:
    runs-on: ubuntu-latest
    name: Python Linter Check

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 

    - name: Install Flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run Flake8 linter check
      run: flake8 .

  tests:
    runs-on: ubuntu-latest
    name: Build and Tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install docker-compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build services
      run: docker-compose -f docker-compose.yml build

    - name: Run tests with test_runner
      run: |
        mkdir -p test-reports
        docker-compose -f docker-compose.yml --profile test up --abort-on-container-exit test_runner
        docker cp test_runner:/app/test-reports/results.xml ./test-reports/results.xml || \
        (mkdir -p test-reports && echo "<testsuites></testsuites>" > test-reports/results.xml)

    - name: Upload test results as artifact
      if: always() # Always run this step, even if previous steps fail
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-reports/results.xml

    - name: Clean up
      if: always()
      run: docker-compose -f docker-compose.yml down
